name: "build-test-on-every-push"

on: push

jobs:
  build:
    name: build test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: '${{ secrets.NODE_VERSION }}'

    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: node_modules
        key: npm-packages ${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: pnpm install

    - name: Build Test
      run: pnpm build
      if: ${{ always() }}